[
    {
        id: 0,
        name: 'Kevin Mitnick',
        pic: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fcleus.co%2Fprogramming-memes%2F&psig=AOvVaw2LGmMkDxVZdGW_BTNqUSTD&ust=1619240260874000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMC1s57Kk_ACFQAAAAAdAAAAABAE',
        profileLink: 'http://www.hackerearth.com/@coding-guru-007',
        location: 'Bangalore',
        education: 'B.Tech',
        challengesSolved: 300,
        solutionsSubmitted: 450,
        solutionsAccepted: 400,
        overallRank: 1118,
        followers: 150,
        following: 55,
        competitivePercentile: {
            dataStructures: 79.1,
            algorithms: 0.0,
            cpp: 89.2,
            java: 55.8,
            python: 88.6,
            html: 92.7,
            javascript: 97.3,
        },
        votes: 5755,
        timestamp: 1234567890,
        deviceType: 'Mobile',
    },
    {
        id: 1,
        name: 'Narendra Modi',
        pic: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Findianmemetemplates.com%2Fmodi-funny-photos%2F&psig=AOvVaw0AdLWQX-go9zFIqtrWYiKc&ust=1619240092998000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNiT_9DJk_ACFQAAAAAdAAAAABAD',
        profileLink: 'http://www.hackerearth.com/@coding-guru-007',
        location: 'Gujarat',
        education: 'B.Tech',
        challengesSolved: 300,
        solutionsSubmitted: 450,
        solutionsAccepted: 400,
        overallRank: 1118,
        followers: 150,
        following: 55,
        competitivePercentile: {
            dataStructures: 79.1,
            algorithms: 0.0,
            cpp: 89.2,
            java: 55.8,
            python: 88.6,
            html: 92.7,
            javascript: 97.3,
        },
        votes: 15684,
        timestamp: 1234567890,
        deviceType: 'Mobile',
    },
    {
        id: 2,
        name: 'Arvind Kejriwal',
        pic: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Findianmemetemplates.com%2Farvind-kejriwal-funny-photos-and-memes%2F&psig=AOvVaw1xmcIzn-tdaTVxLG9xfAoN&ust=1619240168555000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPir1-zJk_ACFQAAAAAdAAAAABAD',
        profileLink: 'http://www.hackerearth.com/@coding-guru-007',
        location: 'Delhi',
        education: 'B.Tech',
        challengesSolved: 300,
        solutionsSubmitted: 450,
        solutionsAccepted: 400,
        overallRank: 1118,
        followers: 150,
        following: 55,
        competitivePercentile: {
            dataStructures: 79.1,
            algorithms: 0.0,
            cpp: 89.2,
            java: 55.8,
            python: 88.6,
            html: 92.7,
            javascript: 97.3,
        },
        votes: 5647,
        timestamp: 1234567890,
        deviceType: 'Mobile',
    },
    {
        id: 3,
        name: 'Mamta Banerjee',
        pic: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DUoOojhj7iFE&psig=AOvVaw2qGZs-QCE5K7w4IgMoKGgj&ust=1619240194918000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCOjq6YDKk_ACFQAAAAAdAAAAABAE',
        profileLink: 'http://www.hackerearth.com/@coding-guru-007',
        location: 'Kolkata',
        education: 'B.Tech',
        challengesSolved: 300,
        solutionsSubmitted: 450,
        solutionsAccepted: 400,
        overallRank: 1118,
        followers: 150,
        following: 55,
        competitivePercentile: {
            dataStructures: 79.1,
            algorithms: 0.0,
            cpp: 89.2,
            java: 55.8,
            python: 88.6,
            html: 92.7,
            javascript: 97.3,
        },
        votes: 2486,
        timestamp: 1234567890,
        deviceType: 'Mobile',
    }
]